### PR TITLE
fix: Build TensorFlow Lite C Framework for x86_64 (simulator) as well

### PR DESCRIPTION
**Pull request by mrousavy**
Builds the TensorFlow Lite C Framework for x86 (64-bit) multi-CPU as well (used in the iOS Simulator)

### CODE REVIEW

**Comment by mrousavy** [comment]
nvm the command I added does not work. I am not even sure if this really is a problem, I had this running on an iOS simulator on arm64. I think this might be an issue with the user's RN app, not with Fast TFLite.

**Comment by Chasty** [comment]
I could not run in simulator for arm64 arch.
@mrousavy

**Comment by computerjazz** [comment]
I'm surprised this is working on arm64 sim for @mrousavy -- There are several open issues suggesting that tflite does not work with arm64 sims:

https://github.com/tensorflow/tensorflow/issues/47400
https://github.com/am15h/tflite_flutter_plugin/issues/153#issue-995240864

In the meantime, i can get it up and running my running a Rosetta simulator

**Comment by computerjazz** [comment]
I just spent a few hours going town a tflite rabbit hole and verified that if I build tflite ONLY for `ios_sim_arm64` it builds and runs in the simulator. However, building for `ios_multi_cpus` and including `ios_sim_arm64` as one of the options fails to build. 

working build command for sim only:
```
bazel build --config=ios_sim_arm64  -c opt --cxxopt=--std=c++17 \                                
  //tensorflow/lite/ios:TensorFlowLiteC_framework
```

non-working build command, hoping to cover all architectures:
```
bazel build --ios_multi_cpus=armv7,arm64,i386,x86_64,ios_sim_arm64  -c opt --cxxopt=--std=c++17 \                                               
  //tensorflow/lite/ios:TensorFlowLiteC_framework
```

So, I'm not seeing a path forward for being able to run on ios sim outside of Rosetta, unless there's a way to include both sim-only and other-cpu binaries in the project and choose which one to include at build time, based on destination architecture.

**Pull request closed without merging**
