### PR TITLE
iOs binaries updated to handle Simulator and Device builds

### PR DESCRIPTION
**Pull request by JoaoPauloCMarra**
Binarie used:
[TensorFlowLiteC.podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/1/6/0/TensorFlowLiteC/0.0.1-nightly.20230212/TensorFlowLiteC.podspec.json#L9C14-L10C201)

related to issues:  #35  #74  #75

### CODE REVIEW

**Comment by mrousavy** [comment]
hey - wow this is cool! can you confirm that this PR builds for you both on an actual iPhone device, and on the Simulator?

**Comment by mrousavy** [comment]
How did you compile those bins? Or did you download them from the link in the podspec you sharedß

**Comment by JoaoPauloCMarra** [comment]
> hey - wow this is cool! can you confirm that this PR builds for you both on an actual iPhone device, and on the Simulator?

It worked for me on both ios device and simulator and eas build.
Yea I got them from the URL in the podspec:

https://dl.google.com/tflite-nightly/ios/prod/tensorflow/lite/release/ios/nightly/794/20230212-035010/TensorFlowLiteC/0.0.1-nightly.20230212/TensorFlowLiteC-0.0.1-nightly.20230212.tar.gz

For now I run a patch to do the same as the PR whenever I install/re-install with --force
Screenshot 2024-08-16 at 09 24 34

Screenshot 2024-08-16 at 09 25 29
locally I log to make sure the patch worked but I removed this log from this PR

**Comment by JoaoPauloCMarra** [comment]
There is a new one from 25min ago:
https://dl.google.com/tflite-nightly/ios/prod/tensorflow/lite/release/ios/nightly/1359/20240816-035010/TensorFlowLiteC/0.0.1-nightly.20240816/TensorFlowLiteC-0.0.1-nightly.20240816.tar.gz

I will try It out and update the PR with It If everything goes well

**Pull request closed without merging**
